begin;

with base_magazine as (
  select
    mt.id as magazine_key,
    mt.magazine_id,
    mt.title as magazine_title,
    mt.title_reading as magazine_title_reading,
    mt.publisher_id,
    mt.publisher_key,
    coalesce(p.publisher_name, '出版社不明') as publisher_name,
    coalesce(p.publisher_reading, 'しゅっぱんしゃふめい') as publisher_reading
  from public.magazine_titles mt
  left join public.publishers p
    on p.id = mt.publisher_key
  where mt.magazine_id = 'M000106'
  limit 1
), upsert_issue as (
  insert into public.magazine_issues (
    magazine_issue_id,
    source_issue_key,
    magazine_id,
    issue_label,
    media_format,
    published_date,
    year,
    month,
    day,
    volume_number,
    issue_number,
    issue_number_displayed,
    sub_issue_number,
    publisher_name,
    price,
    size,
    number_of_pages,
    contents,
    note,
    source_work_count,
    source_first_work_id,
    tags,
    search_text,
    search_reading,
    record_status,
    publisher_id,
    total_issue_number,
    publication_frequency,
    issue_title,
    issue_title_reading,
    subtitle,
    subtitle_reading,
    release_year,
    release_month,
    release_day,
    display_year,
    display_month,
    display_day,
    display_combined_month,
    display_combined_day,
    publication_year,
    publication_month,
    publication_day,
    publication_combined_month,
    publication_combined_day,
    volume_issue_note,
    publishers,
    publisher_person,
    editor_person,
    related_magazines,
    binding,
    magazine_code,
    category,
    rating,
    is_special_issue,
    is_mitsumine,
    magazine_key,
    publisher_key
  )
  select
    'MI0999001',
    'seed_test_mi0999001',
    base.magazine_id,
    'アイラ(2099年01月号) （1-1）通巻999 Vol.999',
    'print',
    '2099-01-15'::date,
    2099,
    1,
    null,
    '1',
    '1',
    '999',
    '',
    base.publisher_name,
    '1200円',
    'A4',
    180,
    '[]'::jsonb,
    'editor-A / super_admin の動作確認用に作成した stories 付き雑誌個別テストデータです。',
    3,
    'S0999001',
    array['テスト', 'stories付き']::text[],
    'MI0999001 アイラ(2099年01月号) （1-1）通巻999 Vol.999 アイラ 三和出版 M000106 999',
    'あいら',
    'published',
    base.publisher_id,
    '999',
    '月刊',
    'アイラ',
    'あいら',
    '',
    'みていぎ',
    2099,
    1,
    15,
    2099,
    1,
    null,
    null,
    null,
    2099,
    1,
    null,
    null,
    null,
    '',
    jsonb_build_array(
      jsonb_build_object(
        'role', '発行',
        'name', base.publisher_name,
        'reading', base.publisher_reading,
        'publisher_key', base.publisher_key,
        'publisher_id', base.publisher_id
      )
    ),
    'テスト発行人',
    'テスト編集人',
    '[]'::jsonb,
    '並製',
    'TEST-0999001',
    array['テスト']::text[],
    '18+',
    false,
    false,
    base.magazine_key,
    base.publisher_key
  from base_magazine base
  on conflict (magazine_issue_id) do update
  set
    source_issue_key = excluded.source_issue_key,
    magazine_id = excluded.magazine_id,
    issue_label = excluded.issue_label,
    media_format = excluded.media_format,
    published_date = excluded.published_date,
    year = excluded.year,
    month = excluded.month,
    day = excluded.day,
    volume_number = excluded.volume_number,
    issue_number = excluded.issue_number,
    issue_number_displayed = excluded.issue_number_displayed,
    sub_issue_number = excluded.sub_issue_number,
    publisher_name = excluded.publisher_name,
    price = excluded.price,
    size = excluded.size,
    number_of_pages = excluded.number_of_pages,
    contents = excluded.contents,
    note = excluded.note,
    source_work_count = excluded.source_work_count,
    source_first_work_id = excluded.source_first_work_id,
    tags = excluded.tags,
    search_text = excluded.search_text,
    search_reading = excluded.search_reading,
    record_status = excluded.record_status,
    publisher_id = excluded.publisher_id,
    total_issue_number = excluded.total_issue_number,
    publication_frequency = excluded.publication_frequency,
    issue_title = excluded.issue_title,
    issue_title_reading = excluded.issue_title_reading,
    subtitle = excluded.subtitle,
    subtitle_reading = excluded.subtitle_reading,
    release_year = excluded.release_year,
    release_month = excluded.release_month,
    release_day = excluded.release_day,
    display_year = excluded.display_year,
    display_month = excluded.display_month,
    display_day = excluded.display_day,
    display_combined_month = excluded.display_combined_month,
    display_combined_day = excluded.display_combined_day,
    publication_year = excluded.publication_year,
    publication_month = excluded.publication_month,
    publication_day = excluded.publication_day,
    publication_combined_month = excluded.publication_combined_month,
    publication_combined_day = excluded.publication_combined_day,
    volume_issue_note = excluded.volume_issue_note,
    publishers = excluded.publishers,
    publisher_person = excluded.publisher_person,
    editor_person = excluded.editor_person,
    related_magazines = excluded.related_magazines,
    binding = excluded.binding,
    magazine_code = excluded.magazine_code,
    category = excluded.category,
    rating = excluded.rating,
    is_special_issue = excluded.is_special_issue,
    is_mitsumine = excluded.is_mitsumine,
    magazine_key = excluded.magazine_key,
    publisher_key = excluded.publisher_key
  returning id, magazine_issue_id, published_date, issue_label
), issue_row as (
  select id, magazine_issue_id, published_date, issue_label
  from upsert_issue
), upsert_story_1 as (
  insert into public.stories (
    story_id,
    story_type,
    series_title,
    series_title_reading,
    episode_number,
    episode_number_sort,
    title,
    title_reading,
    subtitle,
    subtitle_reading,
    contributors,
    page_count,
    is_first_episode,
    is_final_episode,
    first_published_date,
    first_magazine_issue_id,
    status,
    color_info,
    memo,
    tags,
    source_work_ids,
    source_occurrences,
    search_text,
    search_reading,
    record_status,
    first_magazine_issue_key,
    title_reading_core
  )
  select
    'S0999001',
    'serial',
    'テストシリーズA',
    'てすとしりいずええ',
    '第1話',
    1,
    'テスト連載A',
    'てすとれんさいええ',
    '',
    '',
    jsonb_build_array(
      jsonb_build_object('role', '著', 'name', 'テスト作家A', 'author_id', '')
    ),
    32,
    true,
    false,
    issue.published_date,
    issue.magazine_issue_id,
    'active',
    '巻頭カラー',
    'stories 付き雑誌個別テストデータの1件目です。',
    array['テスト', '連載']::text[],
    '[]'::jsonb,
    jsonb_build_array(
      jsonb_build_object(
        'note', '巻頭カラー',
        'year', '2099',
        'volume', '999',
        'position', '1',
        'raw_author', 'テスト作家A',
        'issue_label', issue.issue_label,
        'magazine_title', 'アイラ',
        'publisher_name', '三和出版',
        'source_work_id', 'S0999001',
        'magazine_issue_id', issue.magazine_issue_id
      )
    ),
    'S0999001 テスト連載A テスト作家A 三和出版 アイラ ' || issue.issue_label || ' 巻頭カラー',
    'てすとれんさいええ',
    'published',
    issue.id,
    'てすとれんさいええ'
  from issue_row issue
  on conflict (story_id) do update
  set
    story_type = excluded.story_type,
    series_title = excluded.series_title,
    series_title_reading = excluded.series_title_reading,
    episode_number = excluded.episode_number,
    episode_number_sort = excluded.episode_number_sort,
    title = excluded.title,
    title_reading = excluded.title_reading,
    subtitle = excluded.subtitle,
    subtitle_reading = excluded.subtitle_reading,
    contributors = excluded.contributors,
    page_count = excluded.page_count,
    is_first_episode = excluded.is_first_episode,
    is_final_episode = excluded.is_final_episode,
    first_published_date = excluded.first_published_date,
    first_magazine_issue_id = excluded.first_magazine_issue_id,
    status = excluded.status,
    color_info = excluded.color_info,
    memo = excluded.memo,
    tags = excluded.tags,
    source_work_ids = excluded.source_work_ids,
    source_occurrences = excluded.source_occurrences,
    search_text = excluded.search_text,
    search_reading = excluded.search_reading,
    record_status = excluded.record_status,
    first_magazine_issue_key = excluded.first_magazine_issue_key,
    title_reading_core = excluded.title_reading_core
), upsert_story_2 as (
  insert into public.stories (
    story_id,
    story_type,
    series_title,
    series_title_reading,
    episode_number,
    episode_number_sort,
    title,
    title_reading,
    subtitle,
    subtitle_reading,
    contributors,
    page_count,
    is_first_episode,
    is_final_episode,
    first_published_date,
    first_magazine_issue_id,
    status,
    color_info,
    memo,
    tags,
    source_work_ids,
    source_occurrences,
    search_text,
    search_reading,
    record_status,
    first_magazine_issue_key,
    title_reading_core
  )
  select
    'S0999002',
    'one_shot',
    '',
    '',
    '',
    null,
    'テスト読切B',
    'てすとよみきりびい',
    '',
    '',
    jsonb_build_array(
      jsonb_build_object('role', '原作', 'name', 'テスト原作者B', 'author_id', ''),
      jsonb_build_object('role', '作画', 'name', 'テスト漫画家B', 'author_id', '')
    ),
    24,
    false,
    false,
    issue.published_date,
    issue.magazine_issue_id,
    'active',
    '',
    'stories 付き雑誌個別テストデータの2件目です。',
    array['テスト', '読み切り']::text[],
    '[]'::jsonb,
    jsonb_build_array(
      jsonb_build_object(
        'note', '',
        'year', '2099',
        'volume', '999',
        'position', '2',
        'raw_author', 'テスト原作者B / テスト漫画家B',
        'issue_label', issue.issue_label,
        'magazine_title', 'アイラ',
        'publisher_name', '三和出版',
        'source_work_id', 'S0999002',
        'magazine_issue_id', issue.magazine_issue_id
      )
    ),
    'S0999002 テスト読切B テスト原作者B テスト漫画家B 三和出版 アイラ ' || issue.issue_label,
    'てすとよみきりびい',
    'published',
    issue.id,
    'てすとよみきりびい'
  from issue_row issue
  on conflict (story_id) do update
  set
    story_type = excluded.story_type,
    series_title = excluded.series_title,
    series_title_reading = excluded.series_title_reading,
    episode_number = excluded.episode_number,
    episode_number_sort = excluded.episode_number_sort,
    title = excluded.title,
    title_reading = excluded.title_reading,
    subtitle = excluded.subtitle,
    subtitle_reading = excluded.subtitle_reading,
    contributors = excluded.contributors,
    page_count = excluded.page_count,
    is_first_episode = excluded.is_first_episode,
    is_final_episode = excluded.is_final_episode,
    first_published_date = excluded.first_published_date,
    first_magazine_issue_id = excluded.first_magazine_issue_id,
    status = excluded.status,
    color_info = excluded.color_info,
    memo = excluded.memo,
    tags = excluded.tags,
    source_work_ids = excluded.source_work_ids,
    source_occurrences = excluded.source_occurrences,
    search_text = excluded.search_text,
    search_reading = excluded.search_reading,
    record_status = excluded.record_status,
    first_magazine_issue_key = excluded.first_magazine_issue_key,
    title_reading_core = excluded.title_reading_core
), upsert_story_3 as (
  insert into public.stories (
    story_id,
    story_type,
    series_title,
    series_title_reading,
    episode_number,
    episode_number_sort,
    title,
    title_reading,
    subtitle,
    subtitle_reading,
    contributors,
    page_count,
    is_first_episode,
    is_final_episode,
    first_published_date,
    first_magazine_issue_id,
    status,
    color_info,
    memo,
    tags,
    source_work_ids,
    source_occurrences,
    search_text,
    search_reading,
    record_status,
    first_magazine_issue_key,
    title_reading_core
  )
  select
    'S0999003',
    'extra',
    '',
    '',
    '',
    null,
    'テスト付録C',
    'てすとふろくしい',
    '',
    '',
    jsonb_build_array(
      jsonb_build_object('role', '構成', 'name', 'テスト編集部C', 'author_id', '')
    ),
    8,
    false,
    true,
    issue.published_date,
    issue.magazine_issue_id,
    'active',
    '',
    'stories 付き雑誌個別テストデータの3件目です。',
    array['テスト', '付録']::text[],
    '[]'::jsonb,
    jsonb_build_array(
      jsonb_build_object(
        'note', '付録紹介',
        'year', '2099',
        'volume', '999',
        'position', '3',
        'raw_author', 'テスト編集部C',
        'issue_label', issue.issue_label,
        'magazine_title', 'アイラ',
        'publisher_name', '三和出版',
        'source_work_id', 'S0999003',
        'magazine_issue_id', issue.magazine_issue_id
      )
    ),
    'S0999003 テスト付録C テスト編集部C 三和出版 アイラ ' || issue.issue_label || ' 付録紹介',
    'てすとふろくしい',
    'published',
    issue.id,
    'てすとふろくしい'
  from issue_row issue
  on conflict (story_id) do update
  set
    story_type = excluded.story_type,
    series_title = excluded.series_title,
    series_title_reading = excluded.series_title_reading,
    episode_number = excluded.episode_number,
    episode_number_sort = excluded.episode_number_sort,
    title = excluded.title,
    title_reading = excluded.title_reading,
    subtitle = excluded.subtitle,
    subtitle_reading = excluded.subtitle_reading,
    contributors = excluded.contributors,
    page_count = excluded.page_count,
    is_first_episode = excluded.is_first_episode,
    is_final_episode = excluded.is_final_episode,
    first_published_date = excluded.first_published_date,
    first_magazine_issue_id = excluded.first_magazine_issue_id,
    status = excluded.status,
    color_info = excluded.color_info,
    memo = excluded.memo,
    tags = excluded.tags,
    source_work_ids = excluded.source_work_ids,
    source_occurrences = excluded.source_occurrences,
    search_text = excluded.search_text,
    search_reading = excluded.search_reading,
    record_status = excluded.record_status,
    first_magazine_issue_key = excluded.first_magazine_issue_key,
    title_reading_core = excluded.title_reading_core
), editor_a as (
  select id
  from public.users
  where login_name = 'editor-A'
  limit 1
)
insert into public.application_requests (
  request_id,
  entity_type,
  entity_id,
  title,
  parent_label,
  action,
  status,
  route_path,
  metadata,
  requested_by_user_id,
  submitted_at,
  reviewed_at,
  reviewer_note,
  created_at,
  updated_at
)
select
  'AR000005',
  'magazine_issue_set',
  'MI0999001',
  'アイラ(2099年01月号) （1-1）通巻999 Vol.999',
  'アイラ',
  'create',
  'submitted',
  '/magazines/M000106/issues/MI0999001?from=issue-list',
  jsonb_build_object(
    'note', 'editor-A 実DBテスト用の stories 付き雑誌個別新規申請',
    'magazineId', 'M000106',
    'magazineTitle', 'アイラ',
    'issueTitle', 'アイラ',
    'issueLabel', 'アイラ(2099年01月号) （1-1）通巻999 Vol.999',
    'titleReading', 'あいら',
    'digest', 'stories 3件の実データ付き',
    'recordStatus', 'submitted'
  ),
  editor_a.id,
  now() - interval '5 minutes',
  null::timestamptz,
  '',
  now() - interval '7 minutes',
  now() - interval '5 minutes'
from editor_a
on conflict (request_id) do update
set
  entity_type = excluded.entity_type,
  entity_id = excluded.entity_id,
  title = excluded.title,
  parent_label = excluded.parent_label,
  action = excluded.action,
  status = excluded.status,
  route_path = excluded.route_path,
  metadata = excluded.metadata,
  requested_by_user_id = excluded.requested_by_user_id,
  submitted_at = excluded.submitted_at,
  reviewed_at = excluded.reviewed_at,
  reviewer_note = excluded.reviewer_note,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at;

commit;
